# This file was generated by GoReleaser. DO NOT EDIT.
cask "flowbaton" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "28a642dc29613d439c34350bd3517cee7dc48da75c8d1ae55e52fe8bd043e47f"
      url "https://github.com/larchwave/flowbaton/releases/download/v#{version}/flowbaton_#{version}_darwin_amd64.tar.gz"
      rename "flowbaton_0.1.0_darwin_amd64/flowbaton", "flowbaton"
    end
    on_arm do
      sha256 "7cbc7f0dc939773f5b9dacd61915ca19b3b277ec2c89092b4675008898365ada"
      url "https://github.com/larchwave/flowbaton/releases/download/v#{version}/flowbaton_#{version}_darwin_arm64.tar.gz"
      rename "flowbaton_0.1.0_darwin_arm64/flowbaton", "flowbaton"
    end
  end

  on_linux do
    on_intel do
      sha256 "900853867a4ac0f4da39e08306690765c39b8f3d88e593ac20e88c046d2f73bf"
      url "https://github.com/larchwave/flowbaton/releases/download/v#{version}/flowbaton_#{version}_linux_amd64.tar.gz"
      rename "flowbaton_0.1.0_linux_amd64/flowbaton", "flowbaton"
    end
  end

  name "flowbaton"
  desc "Pre-alpha mobile UI automation toolkit: Go CLI, Android agent, iOS Simulator runner"
  homepage "https://github.com/larchwave/flowbaton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flowbaton"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flowbaton"]
    end
  end

  # No zap stanza required

end
