# This file was generated by GoReleaser. DO NOT EDIT.
cask "flowbaton" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "0c24b21d744f6164e1e86f36617d02ddd832fdccf25e61ec6f6c43f3e02ce766"
      url "https://github.com/larchwave/flowbaton/releases/download/v#{version}/flowbaton_#{version}_darwin_amd64.tar.gz"
      rename "flowbaton_0.1.1_darwin_amd64/flowbaton", "flowbaton"
    end
    on_arm do
      sha256 "a28ec381545fff655091ad6c35d4d50e4162304ea13806ba4bdd905639751f2f"
      url "https://github.com/larchwave/flowbaton/releases/download/v#{version}/flowbaton_#{version}_darwin_arm64.tar.gz"
      rename "flowbaton_0.1.1_darwin_arm64/flowbaton", "flowbaton"
    end
  end

  on_linux do
    on_intel do
      sha256 "82987aa0af5c8b979058170394a661323867ce33aeb806042c20f3912e9ac5e7"
      url "https://github.com/larchwave/flowbaton/releases/download/v#{version}/flowbaton_#{version}_linux_amd64.tar.gz"
      rename "flowbaton_0.1.1_linux_amd64/flowbaton", "flowbaton"
    end
  end

  name "flowbaton"
  desc "Pre-alpha mobile UI automation toolkit: Go CLI, Android agent, iOS Simulator runner"
  homepage "https://github.com/larchwave/flowbaton"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "flowbaton"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/flowbaton"]
    end
  end

  # No zap stanza required

end
